# rusty_xkcd GitLab CI script
stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo fmt --verbose -- --check
    - cargo clippy --all-targets --verbose
    - cargo check --all-targets --verbose
    - cargo build --verbose --all
    - cargo test --verbose --all

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo fmt --verbose -- --check
    - cargo clippy --all-targets --verbose
    - cargo check --all-targets --verbose
    - cargo build --verbose --all
    - cargo test --verbose --all
  allow_failure: true
