# rusty_xkcd Travis CI script
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
# Install rustfmt and clippy
install:
  - cargo build
  - rustup component add rustfmt
  - rustup component add clippy
# Run build script
# rustfmt
# clippy
# build
# test
# benchmark
script:
  - cargo fmt -- --check --verbose
  - cargo clippy --all-targets
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench --verbose
