# rusty_xkcd Travis CI script
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
install:
  - rustup update
  - rustup self update
  - cargo update
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --verbose -- --check
  - cargo clippy --all-targets --verbose
  - cargo check --all-targets --verbose
  - cargo build --verbose --all
  - cargo test --verbose --all
