language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
install:
  - cargo build
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo --fmt --all -- --check
  - cargo clippy --all-targets
  - cargo build
  - cargo test --verbose --all
  - cargo doc --verbose --all
