# rusty_xkcd Appveyor script
environment:
  matrix:
    - TARGET: 1.13.0-x86_64-pc-windows-gnu
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: nightly-x86_64-pc-windows-gnu
    - TARGET: nightly-i686-pc-windows-gnu
matrix:
  allow_failures:
    - channel: nightly
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
  - rustup update
  - rustup self update
  - cargo update
  - rustup component add rustfmt
  - rustup component add clippy
build: false
test_script:
  - cargo fmt --verbose -- --check
  - cargo clippy --all-targets --verbose
  - cargo check --all-targets --verbose
  - cargo build --verbose --all
  - cargo test --verbose --all
